language: node_js
node_js:
    - "12"

services:
    - mongodb

script:
    - yarn install
    - cd protocol
    - yarn build
    - yarn test
    - cd ../server
    - yarn build
    - yarn test
    - cd ../client
    - yarn build
    - yarn test
