language: node_js
node_js:
    - "12"

services:
    - postgresql

cache:
    directories:
        - ./.yarn/cache

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - yarn -v

install:
    - yarn install

env:
    - NODE_ENV=production

script:
    - yarn build
    - cd engine
    - yarn test
    - cd ../server
    - cp .env.test .env
    - yarn test
    - cd ../client
    - yarn build
    - yarn test
