language: node_js
node_js:
    - "12"

services:
    - mongodb

cache:
    directories:
        - ./.yarn/cache

before_install:
    # Upgrade Yarn 1.x: https://classic.yarnpkg.com/en/docs/install
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    # Then the local Yarn 2 should be available and get used
    - yarn -v

install:
    - yarn install

script:
    - cd engine
    - yarn build
    - yarn test
    - cd protocol
    - yarn build
    - yarn test
    - cd ../server
    - yarn build
    - yarn test
    - cd ../client
    - yarn build
    - yarn test
